javascripts:
  jquery:
    - public/javascripts/jquery-1.5.1.min.js
    
  jquery_ui:
    - public/javascripts/jquery-ui-1.8.10.custom.min.js
    
  jquery_plugins:
    - public/javascripts/jquery.media.js
    - public/javascripts/jquery.simplezoom.js

  application:
    - public/javascripts/rails.js
    - public/javascripts/application.js

stylesheets:
  reset:
    - public/stylesheets/reset.css

  theme:
    - public/stylesheets/base.css
    - public/stylesheets/warehouseTheme.css

  theme_mods:
    - public/stylesheets/formtastic.css
    - public/stylesheets/charas.css

  controllers:
    - public/stylesheets/controllers/**/*.css